version: "3.9"

services:
  mongodb:
    image: mongo
    env_file:
      - .env.mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: on-failure
volumes:
  mongodb:

